### ISSUE TITLE
Menu minor issue

### ISSUE THREAD

**Issue by rdellwebworks** [presscustomizr/customizr#449] opened 2015-12-05 11:14 UTC
Have noticed on some of my sites and other sites in the Forum. Czr puts a thick border around a menu item when hovering and selecting it. Menu item is center/middle EXCEPT the first and last items.

Traced the 'last' use-case to this code:
.logo-left .navbar div > ul.nav > .menu-item:last-child > a, .pull-menu-right .navbar div > ul.nav > .menu-item:last-child > a, .tc-header .btn-toggle-nav.pull-right {
  padding-right: 0;
}
Remove the padding-right and it works OK.

'First' use-case is:
.pull-menu-left .navbar div > ul.nav > .menu-item:first-child > a, .tc-header .btn-toggle-nav.pull-left {
    padding-left: 5px;
}

Examples: http://www.blackcombconsultants.com  http://www.rdell.co.uk/

**Comment by eri-trabiccolo** [comment] 2015-12-05 11:27
Hello Dave,
thanks for this.
Actually that rule has a meaning, we want that when the logo is on the left and/or the menu is on the right the last child menu item link should have no padding right so it's aligned with the right edge of the tagline.

I cannot reproduce this border thing though, do we put borders on active/hover/focused elements?
Can you give me an example?

Thanks Dave ;)

**Comment by rdellwebworks** [comment] 2015-12-05 11:36
2 sites above are examples. On my rdell site, if you click on Home and Consulting you get the #08C blue border when you click on the link.

Noticed it some time ago but never diagnosed why.

**Comment by eri-trabiccolo** [comment] 2015-12-05 12:20
But I cannot see the border.
Is something like this?
![focus](https://cloud.githubusercontent.com/assets/7689242/11607708/88d5b62a-9b52-11e5-9a0a-44c02efc8ecb.png)

If yes, it's about the outline on :focus 
Weird enough I couldn't reproduce it with my browsers (I had to force it), with which browser you can?
So this should fix it:
`.nav-collapse .nav li a:focus {
    outline: none;
}`
To remove the outline completely, as I don't think we want to renounce to the alignment stuff above.

Let me know if it's that.

**Comment by rdellwebworks** [comment] 2015-12-05 12:36
I use FF Developer. But your fix works, thanks!

**Comment by rdellconsulting** [comment] 2015-12-05 12:38
https://www.dropbox.com/s/zkt4nyn6zmnpbn2/Screenshot%202015-12-05%2012.29.02.png?dl=0

 

You’re right. I use FF Developer.

 

I can’t close the Issue?

**Comment by eri-trabiccolo** [comment] 2015-12-05 12:44
Glad to hear that.
Let's keep this open, I'll push a PR referencing to this and we'll close the issue when and if the PR will be merged.
Thanks Dave, have a great w-e!

Rocco

**Comment by eri-trabiccolo** [comment] 2015-12-10 15:28
Dave, we finally decided to keep this as is for now.
Outline is used by the readers (see accessibility), and we don't want to renounce to the alignment as said above :)
A solution would be "transform" menu items link paddings in margins so the outline will always wrap just the "words" and margins will allow us to keep the alignment.
A decision on this, hence the implementation, will be taken when porting Customizr to a new html/css/js framework (Bootstrap4 or similar).
We'll keep this open till then, so we'll remember it (hopefully ;))

**Comment by rdellconsulting** [comment] 2015-12-10 16:01
Thanks for the headsup. Explains why the Outline is so thick. Was just one of those things I noticed some time ago and never had the chance to understand it.

**Closed** 2016-01-25 13:29 UTC
Labels: bug
