### ISSUE TITLE
tc_opt_tc_menu_style filter missing

### ISSUE THREAD

**Issue by menakas** [presscustomizr/customizr#675] opened 2016-11-04 06:08 UTC
As per this comment on the disqus forum, the filter _tc_opt_tc_menu_style_ is missing. I too could not find it in the code.

**Comment by eri-trabiccolo** [comment] 2016-11-04 08:59
Hello @menakas ,
thanks for reporting this.

What do you mean with _is missing_ ?
That you cannot use the filter hook? We can here...
 
If you talk about the fact that is not plain visibile in the code, that's because its, as well as all the theme options filters, is dynamically generated here:
https://github.com/presscustomizr/customizr/blob/master/inc/_dev/class-fire-utils.php#L329

when you request an option with CZR_utils::czr_fn_opt('tc_option_name'), the value is returned through the filter hook 'tc_opt_tc_option_name'.

**Comment by eri-trabiccolo** [comment] 2016-11-15 18:20
Hi @menakas 
any news on this?
Couldn't reproduce the issue, could you?

**Comment by menakas** [comment] 2016-11-16 04:26
No @eri-trabiccolo. I too could not reproduce this. Yes, I realized that the option is being dynamically generated. Thanks for pointing that out.

**Comment by eri-trabiccolo** [comment] 2016-11-16 10:41
Thanks for the feedback @menakas 
I propose to close this issue @nikeo , the filter is there and we can use it.

**Closed** 2019-11-28 13:48 UTC
Labels: question, wontfix
