### ISSUE TITLE
WPGlobus issue, multilingual?

### ISSUE THREAD

**Issue by rdellwebworks** [presscustomizr/customizr#509] opened 2016-01-18 15:11 UTC
Originally fixed in 3.4.14 but language issue?

https://wordpress.org/support/topic/wpglobus-and-customizr

**Comment by eri-trabiccolo** [comment] 2016-01-20 12:55
Thanks Dave.
Don't think it's theme related honestly.
I'm not able to reproduce it here.
Will keep this open till we'll get an user's feedback.

**Comment by eri-trabiccolo** [comment] 2016-01-20 15:50
User confirmed was a permalink issue not theme related then.
Closing this ;)

**Closed by eri-trabiccolo** 2016-01-20 15:50 UTC
Labels: question
