### ISSUE TITLE
Horizontal Menu Bug : child items might go off screen when revealed

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/customizr#369] opened 2015-10-28 07:29 UTC
Hi,

I am able to replicate this issue on my computer.

1) Set a horizontal menu.
2) Set the menu to right position
3) For the last menu item on the right, at a sub -> sub menu item (third level)
When you hover over it, the third level menu item disappears.

Customer on the following thread reported this issue.
https://secure.helpscout.net/conversation/133887559/2536/

Thanks!
Denzel

**Comment by Nikeo** [comment] 2015-10-28 07:31
OK thanks for reporting Denzel

**Comment by eri-trabiccolo** [comment] 2015-10-28 07:40
Hello Denzel, do you mean that it goes off the screen?

**Comment by denzelchia** [comment] 2015-10-28 07:42
Hi Rocco,

Yes, I mean it goes off the screen.
Sorry for using the wrong word.

Thanks!
Denzel

**Comment by eri-trabiccolo** [comment] 2015-10-28 07:47
Don't worry Denzel :)
It's just that I was unable to reproduce the "disappearing".
Yes this is a known bug, I'm so used to it that I just don't notice it :D

**Comment by denzelchia** [comment] 2015-10-28 07:48
Thank you! :)

**Comment by Nikeo** [comment] 2015-10-28 08:01
For now, the only fix I can see would be to make the menu smarter and let it detect if an item goes off screen...
Any idea welcome ? Javascript will be our friend

**Comment by eri-trabiccolo** [comment] 2015-10-28 08:09
I remember I started some js long ago to fix this .. it was a little tricky understand the "off screen" because of the fact that hidden elements are hard to manage with jquery (sizes, positioning) + the "arrow" should be moved too.
Maybe we can move the items just when displayed (hover on the parent) - have to look at the transitions effects too.

**Comment by Nikeo** [comment] 2015-10-28 08:11
yep I remember that too.
OK I add this to the scheduled devs in azzzzzzana

**Comment by eri-trabiccolo** [comment] 2015-11-19 21:32
I decided to do the "moving" on window's resize.
The thing is that to do it when the element's about to appear means that we have to deal with different events, such as mousenter, click, touchstart and so on.
Also because the moving acts after the element's appears you might see it while moving to the new position (accentuated when transitions are on, e.g. when Reveal the sub-menus blocks with a fade effect option is enabled) + some kind of "re-computing" should be done on resize because, when a submenu is open on click you can still re-size the window while it's open.
I think isn't overall a big deal doing it on resize. Most likely a common user resizes less times than how it opens submenus, and considering that to keep a certain consistency we should still reset our positioning alteration each time a submenu is opened ..
Anyway the code is quite done (it might appear long and convoluted but it's not, don't worry Nico :P, most of that are "comments").
I'm currently building it as "snippet" in my child-theme functions.php, for simplicity so.. I think I can share it once done ( even if Nico might want to go for a different solution :) ) so that Denzel can share it as temporary patch to the users till we finally merge it into the core.

**Comment by denzelchia** [comment] 2015-11-20 09:04
Thank you for sharing these information.

**Comment by eri-trabiccolo** [comment] 2015-11-27 12:51
Pushed a PR about this.
I tested it with and without the sidenav, with and without the second menu on, and in the latter case moving the second menu inside the sidenva, hiding it or keep it in the header.
As it's a bit mind-blowing a double check might help :)

**Closed** 2015-12-08 10:42 UTC
Labels: bug, dev-planned, fixed
