### ISSUE TITLE
Thrive leads plugin compatibility issue

### ISSUE THREAD

**Issue by menakas** [presscustomizr/customizr#643] opened 2016-10-03 07:05 UTC
Based on this issue in the support forum
[https://wordpress.org/support/topic/thrive-leads-plugin-issue/#post-8237471](https://wordpress.org/support/topic/thrive-leads-plugin-issue/#post-8237471)
there seems to be some compatibility issue with the Thrive leads plugin.
Not able to reproduce this issue because it is a paid plugin.

**Comment by eri-trabiccolo** [comment] 2016-10-03 07:45
Hello @menakas ,
thanks for this.
If the problem is the one in the screenshot we can solve it. Though we didn't do any change related to that recently.
Will provide a PR soon.

Bests.

**Comment by eri-trabiccolo** [comment] 2016-10-03 08:48
According to the screenshot provided in the wp.org topic above the issue was reported here too:
https://wordpress.org/support/topic/fix-to-tc-scriptsminjs-to-allow-for-custom-page-templates/

**Comment by eri-trabiccolo** [comment] 2016-10-07 08:39
Reported also by pro user here:
https://secure.helpscout.net/conversation/260045861/18089/?folderId=607709

Temporary snippet to add to the child-theme to avoid the issue (applied to all the pages though):
https://gist.github.com/eri-trabiccolo/4c49d8292a30db5c8ed1786622c7a0b3#file-disable_dropdown_placement-php

Fixed in #644

**Comment by menakas** [comment] 2016-10-07 08:49
Thanks @eri-trabiccolo 
Passed it on to the user

**Comment by eri-trabiccolo** [comment] 2016-10-07 09:30
thanks @menakas

**Closed** 2016-10-12 08:36 UTC
Labels: bug, fixed
