### ISSUE TITLE
Using the word span in slider name causes conflict

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/customizr#521] opened 2016-01-25 06:30 UTC
Hi,

With reference to this helpscout thread.
https://secure.helpscout.net/conversation/163391356/7470/?folderId=631714

On my localhost WordPress installation with only Customizr Pro and no plugins activated.

The following are steps I took to replicate this issue.
1) Add an image
2) Create a slider and name it span-slider
    http://i.imgur.com/zjcjebK.png
3) Attach slider to homepage
4) View slider and you will see that it's broken. Does not slide, controls gone, and slider is not full width.
    http://i.imgur.com/CpKqcJp.jpg

Could be cause by conflict with css from inc/assets/css/tc_common.min.css as reported by customer.

Thank you,
Denzel

**Comment by eri-trabiccolo** [comment] 2016-01-25 07:55
Hello Denzel,
thanks for reporting this.
Yes we're aware of this.
The problem is about the large use of the "span" word as css class wild card in the whole bootstrap2 CSS (and sometimes by our custom css too).
We had(still have) a similar issue with the alternate layout when articles have a tag like "span" (e.g. "spanish"), as the article element in the alternate layout is a ".row-fluid" it happens to match also the CSS rules for "span"..  [ I remember I provided a workaround for that on the wporg forum, have to see if I can find it]

I don't think we can do that much for this specific issue as it mostly depends on b2 and .
We'll see.

**Comment by denzelchia** [comment] 2016-01-25 09:15
Thank you for the explanation!

**Comment by eri-trabiccolo** [comment] 2016-01-25 09:55
You're always welcome Denzel,
and thanks for raising this.

**Comment by eri-trabiccolo** [comment] 2016-01-25 10:29
Hello Denzel,
that's the topic I was referring to:
https://wordpress.org/support/topic/nav-below-too-high-and-overlap-post-in-home#post-5454163

**Comment by Nikeo** [comment] 2016-01-25 15:27
let's close it now and wait for the new css framework to be impemented.

**Closed by Nikeo** 2016-01-25 15:27 UTC
Labels: bug, question
