### ISSUE TITLE
Some strings in Appearance -> Customize is missing from po file

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/customizr#552] opened 2016-02-10 08:01 UTC
Hi,

With reference to this helpscout thread.
https://secure.helpscout.net/conversation/168833001/8711/?folderId=631714

I used this plugin https://wordpress.org/plugins/loco-translate/
to search for the string "Enable the Grid Customizer" which is found in Appearance -> Customize -> Content -> Post lists
I was not able to find it in the hebrew po file.
I also wasn't able to find it in the french po file.

I tried to use the plugin to scan and update the po files, but it wasn't able to include the strings.

These are the strings that I was not able to find in po file.
http://i.imgur.com/W5lZEoI.jpg

Thank you,
Denzel

**Comment by eri-trabiccolo** [comment] 2016-02-11 13:51
Hello Denzel,
pro contents lang files are in the specific addon dir, in this case in addons/bundle/lang/
Anyways the file you'll find there is incomplete/wrong at the moment.
Thanks for raising this!
(we'll probably close this issue and #551 moving them among the pro issues ;))

**Closed** 2016-02-11 16:34 UTC
Labels: bug

**Comment by denzelchia** [comment] 2016-02-12 03:52
Hi Rocco,

Sorry to bother.

Customer is asking if it's possible to provide the updated files to him?
Customer is also asking whether you can include his translated hebrew pro file into Customizr Pro Theme. 

This is the po file link 
https://secure.helpscout.net/file/a2c052e13143a445/88820/438338601/33643007/he_IL/

This is the mo file link
https://secure.helpscout.net/file/a2c052e13143a445/88820/438338601/33643006/he_IL/

Thank you,
Denzel

**Comment by dotanshema** [comment] 2016-02-12 07:05
If possible, please combine all the strings addon to the main translation file.
If this is not possible, just send me your updated files.

**Comment by denzelchia** [comment] 2016-03-16 06:10
Hi Rocco,

I have another customer reporting unable to translate some strings in Appearance -> Customize -> Content -> Featured pages.
As well as Appearance -> Customize -> Font Customizer

https://secure.helpscout.net/conversation/181669701/11105/?folderId=631714

I enabled french language and I am able to see those strings untranslated.
Please let me know if I need to open a new issue.

Maybe you are already working on these?

Thank you
Denzel

**Comment by eri-trabiccolo** [comment] 2016-03-16 08:52
Hi Denzel,
thanks for the report.
Which kind of problem with the Featured Pages? I can see the translations.. where they're set (in italian). Maybe the default po file is old and needs to be updated. Is this the problem? Anyway updating from source before translating is always a good practice.
About WFC the problem is that the strings are "parsed" before the textdomain is loaded, we'll look into it.

**Comment by denzelchia** [comment] 2016-03-16 09:55
Hi Rocco,

Thank you for your advise.
I have updated the strings in customer's po file and pass back to customer.

Thank you.
