### ISSUE TITLE
FW0032 Border around links in FF

### ISSUE THREAD

**Issue by rdellwebworks** [presscustomizr/customizr#538] opened 2016-01-31 11:15 UTC
https://wordpress.org/support/topic/borders-around-all-links-since-update

I raised this with Rocco some time ago - don't remember the solution sorry!

**Comment by rdellwebworks** [comment] 2016-01-31 11:20
Found it.

**Comment by eri-trabiccolo** [comment] 2016-01-31 11:27
Cannot see these borders the user reported.
He says all links, so not only the menu ones?

Anyway this should be the issue you reported before:
https://github.com/presscustomizr/customizr/issues/449

**Comment by rdellwebworks** [comment] 2016-01-31 11:33
I can reproduce in FF. It is affecting all a links. Been trying to fix but not found solution yet.

**Comment by eri-trabiccolo** [comment] 2016-01-31 11:33
Can you share a screenshot?

I can't reproduce it
Steps?

**Comment by rdellwebworks** [comment] 2016-01-31 11:33
Try rt-click on the link and see if that reproduces it for you

**Comment by eri-trabiccolo** [comment] 2016-01-31 11:35
Nope it doesn't.
FF on windows? version?

**Comment by eri-trabiccolo** [comment] 2016-01-31 11:38
But.. is always about the outline, is that the border we're talking about?

**Comment by rdellwebworks** [comment] 2016-01-31 11:38
Win 10 FF Developer 46.0a2
![border](https://cloud.githubusercontent.com/assets/11431088/12701841/27a1d8fe-c80f-11e5-9977-157598bd31ab.PNG)

**Comment by eri-trabiccolo** [comment] 2016-01-31 11:43
The thing is that we haven't changed anything in the CSS for that.
So it's always the same thing, I don't think it depends on the update, it might depend on firefox.
It depends on the "focus" state of the link.
That's the outline when the links are focused. As said in the issue closed it's for readers:
> Outline is used by the readers (see accessibility)

Does the following  solve the issue?
`btn:focus, a:focus { outline: none !important;}`

So you can reproduce the same with the demo site too, right?

**Comment by rdellwebworks** [comment] 2016-01-31 11:47
Not tried Demo, but was a problem before. This seems to fix it.

**Comment by rdellwebworks** [comment] 2016-01-31 11:56
User reported [resolved]

Thanks Roc

**Comment by eri-trabiccolo** [comment] 2016-01-31 12:01
Well anyway..
that's needed for readers, it's not an issue. With elements which have "asymmetric" padding can be ugly.
We can get rid of the outline and instead color the link with the "hover" color.. boss decision :) 
Anyway consider that the outline thing, if I'm not wrong, was taken from bootstrap2 css

Still we didn't change it in the latest releases, probably no changes to that have been made since the use of the less files (>1y ago), so.. the only one reason can be a change in firefox (?!) [ still not a wrong thing imho].

Glad that simple code was useful ;)

**Comment by Nikeo** [comment] 2016-01-31 14:27
Accessibility accessibility... :)

Font Awesome ! :D

**Comment by Nikeo** [comment] 2016-01-31 14:27
Font Awesome Font Awesome Font Awesome

**Comment by eri-trabiccolo** [comment] 2016-01-31 16:59
eheh

**Comment by Nikeo** [comment] 2016-02-04 08:53
also reported in #543 
This is related to the latest version of FF, v44+

![2016-02-04_09-33-03](https://cloud.githubusercontent.com/assets/3038156/12809867/a8c018b8-cb22-11e5-9204-c20a4f254007.png)
![bug_1](https://cloud.githubusercontent.com/assets/3038156/12809869/ad3ffab6-cb22-11e5-8a1f-e9bb64229941.png)

Unlike other browser, the focus outline property is displayed on click with FF.
For chrome, you can see the focused link without the dev tool by simply using the tab of your keyboard to navigate in the website. This is the normal accessibility feature that we have to keep.
https://www.w3.org/TR/2008/REC-WCAG20-20081211/#navigation-mechanisms-focus-visible

### The first change would be to replace
`outline: 5px auto @lnkColLightenlinkColor;`
by
`outline: thin auto @lnkColLightenlinkColor;`
here
https://github.com/presscustomizr/customizr/blob/dev/inc/assets/less/tc_skin_rules.less#L11

### Then understand why it's handled like this in FF
and find a fix to disable the outline being displayed on click.

**Comment by eri-trabiccolo** [comment] 2016-02-04 09:28
Tried to use the jquery `blur()`(which should remove the focus state) on click. Doesn't work either.

**Comment by eri-trabiccolo** [comment] 2016-02-04 09:50
I still think it's a ff bug :D 
Anyway -> http://a11yproject.com/posts/never-remove-css-outlines/
the second suggested script -> https://github.com/lindsayevans/outline.js/blob/master/outline.js
with really small modifications works fine.
Do we want to include it? And if yes do we want to limit this to firefox? (browser check...)

**Comment by Nikeo** [comment] 2016-02-04 10:01
yes let's include one of those scripts with a browser side js condition : must be firefox

**Comment by eri-trabiccolo** [comment] 2016-02-04 10:53
do you still want the outline css change in the skin ? (you know what I mean :P)

**Comment by eri-trabiccolo** [comment] 2016-02-17 07:55
from Denzel:

> A customer has feedback that the temporary fix does not work for radio button and checkboxes.
> 
> https://secure.helpscout.net/conversation/170823163/9099/?folderId=631714#thread-445583824

**Closed** 2016-02-17 08:38 UTC
Labels: enhancement, fixed, Urgent
