### ISSUE TITLE
WooCommerce image issue

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#712] opened 2016-12-25 10:15 UTC
After update to Customizr Pro 1.2.36 ver i dont have img product in me woocommerce snop

**Comment by eri-trabiccolo** [comment] 2017-01-05 16:11
cannot reproduce :/

**Comment by Nikeo** [comment] 2017-01-05 16:11
me neither...

**Comment by ElectricFeet** [comment] 2017-12-09 15:47
I had this in another theme where I had some functions.php code that removed the featured images from posts and pages. I hadn't realised that the woocommerce product pages fire `is_single()`. Resolved with `is_single() && (! is_product() )`. Could be this have been the cause?

I'd close this after a year without any more info.

**Closed** 2019-11-28 13:49 UTC
Labels: bug, cant-reproduce, question, wontfix
