### ISSUE TITLE
A fine line visible in split second when hovering our Featured Pages Thumbnail

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/customizr#474] opened 2015-12-24 04:01 UTC
Hi,

With reference to this thread reported on Help Scout.
https://secure.helpscout.net/conversation/153280148/5569/?folderId=631714

Using my Safari Desktop Browser ( Version 9.0.2 )
I visited customer's website ( http://mrbillows.com/ ) and is able to see the issue.

When I mouse over one of the featured pages image. 
For a split second, I can see a fine line on the right side of the image.
Please see screenshot for explanation. http://i.share.pho.to/11254b88_o.png

This also happens on our demo site.
Please see screenshot for explanation. http://i.share.pho.to/c31daa5e_o.png

I am only seeing this issue on Safari Browser.
Not seeing this on Firefox or Chrome.

Best Regards,
Denzel

**Comment by Nikeo** [comment] 2015-12-24 08:05
thanks for reporting this Denzel. I've been struggling with this issue long time ago and could not find the perfect solution for all browsers.

**Comment by eyelanoesis** [comment] 2016-05-30 12:42
Hi Nikeo, as always, thanks for the work, the theme etc.
I really need a fix or temporary workaround for this issue..
One of my clients as switched to OSX (and safari) and he is now very unhappy with the customizr site that I set up for him (he used to be VERY satisfied)
What are the chances of a fix in the near future?

**Comment by eri-trabiccolo** [comment] 2016-05-30 13:18
Could you try if this hack produces any relevant result?
for pro:
`
.fpc-widget-front .thumb-wrapper img {
  border: 4px solid transparent;
  box-sizing: border-box;
}
`
for customizr free : 
`.widget-front .thumb-wrapper img {
  border: 4px solid transparent;
  box-sizing: border-box;
}`

**Comment by eyelanoesis** [comment] 2016-05-30 13:37
Hi Eri, thanks for your swift reply :)
Your fix works with 3 featured pages per line, but not with 4 as I need :)

**Comment by eri-trabiccolo** [comment] 2016-05-30 15:46
I see, this is very annoying looks like safari's overflow: hidden differently treats the "cut off" of the inner elements (in this case the border of an element and an image)

**Comment by eri-trabiccolo** [comment] 2016-05-31 14:10
I just thought that it might be those kind of graphical issue that can be solved using the gpu.
Can you check if the following CSS changes anything?
`
.thumb-wrapper, .round-div {
  -webkit-transform: translateZ(0);
              transform: translateZ(0);
}
`

**Comment by eyelanoesis** [comment] 2016-05-31 17:30
Using it in conjunction with your first suggestion it makes the vertical stripes appear constantly.

**Comment by eyelanoesis** [comment] 2016-05-31 17:33
If you want to test it on my staging install I made you a user.
Usr: Eri
pw: trabiccolo

**Comment by eri-trabiccolo** [comment] 2016-05-31 17:36
Not in conjunction, replace the former with the new one.
Thanks for the account but the problem is that it happens on mac safari and I cannot test it in the short time.
I just used some kind of emulator, and the second (without the first) looked fine..
Doesn't it then?

**Comment by eyelanoesis** [comment] 2016-06-01 12:13
Adding it to custom css as the only entry does the same as adding it in conjunction with the former fix.
I am pretty rusty with HTML and CSS so I don't have time to figure out how to apply the rule to the image at present. Also, that would be far from an optimal solution as the client needs to be able to change the featured images on his own.

**Comment by eri-trabiccolo** [comment] 2016-06-01 12:26
with "apply the rule to the img" meant just add this rule to your custom CSS:
` .thumb-wrapper img { -webkit-transform: translateZ(0); transform: translateZ(0); }`
that will target all the img elements inside an element with a CSS class "thumb-wrapper", so it doesn't depend on the single image the user choose, is a general CSS which applies to all the images respecting the condition aforementioned ;)
So the important thing is that having the following rule (without the one suggested here:https://github.com/presscustomizr/customizr/issues/474#issuecomment-222490937) in your custom CSS:
` .thumb-wrapper, .round-div, .thumb-wrapper img { -webkit-transform: translateZ(0); transform: translateZ(0); } `
doesn't fix the issue at all.
Right?

**Comment by eyelanoesis** [comment] 2016-06-01 13:00
Understood.
Yes, when applying the new rules, the vertical lines merely remain constant rather only being triggered on mouseover

**Comment by eri-trabiccolo** [comment] 2016-06-01 13:05
I see,
thanks for the feedback! We'll try to find a fix for this safari's issue.

**Comment by eyelanoesis** [comment] 2016-06-01 13:20
If you don't need access to my test site I'll delete the account

*Rune Abro, Ph.B*
Abstreet Media Productions
Photography & Design -  Music & Sound - Video -Text etc
www.Abstreet.info <http://www.abstreet.info/>

Daylight broke me loose and brought me back
Rμηε αβrσ αd. - Runes anonymus
Haidzruno runu, falahak haidera, ginnarunaz.

**Comment by eri-trabiccolo** [comment] 2016-06-01 14:28
Yes, not needed thanks. You can proceed with the deletion. ;)

**Comment by eri-trabiccolo** [comment] 2016-08-26 07:37
Still not solution for this safari related issue.
Also it doesn't happen with all the safari version.
It really looks a rendering bug for pretty recent safari versions.
So the only real thing to avoid that as of now is to renounce to the hover effect + rounded shape adding the following css:
`.safari .fpc-widget-front .round-div { border-color: transparent !important; }`
:(

**Closed** 2019-11-28 13:36 UTC
