### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by rdellwebworks** [presscustomizr/customizr#393] opened 2015-11-09 11:34 UTC
Updating from 1.2.7 to 1.2.12 giving error:
![untitled picture](https://cloud.githubusercontent.com/assets/11431088/11032760/da7754f2-86d5-11e5-94a3-7ed54c261bb6.png)

**Comment by eri-trabiccolo** [comment] 2015-11-09 11:42
Ohhhh you had this error we're aware of but that we're unable to reproduce :D
Since that file hasn't changed, what could be the reason?
Also looks like that issue happens just with WAMP.
My guess was that it has to do with the PATH length limits in Window's filesystems.
In my idea, the problem is that when you download the update it gets saved in wp-content/uploads/
and its name is that long hash you see in the url, which is very long. That file gets unpacked and the dir with the same name will contain the theme's tree (so the PATHS will become even longer).
This is the only idea which still stands.
You can google for the error message "An error occured while updating Custoimzr Pro: Could not copy file"
The other reason might be related, instead, to the extension of that file, and this is a server settings, you have to see if there's a way to act on them. Not sure how.. :| (google)
Dunno what we can do about that :( but the fact that you can reproduce it is a good sign :D

**Comment by rdellwebworks** [comment] 2015-11-09 11:45
It's my localhost copy, using XAMPP.

**Comment by eri-trabiccolo** [comment] 2015-11-09 11:51
ok XAMPP on Windows is WAMPP :)

**Comment by Nikeo** [comment] 2015-11-09 16:53
I would tend to think it's related to the length too.

Anyway : if you only get this problem with Customizr Pro, please close this issue : this should not be reported here since we collect only issues about Customizr free here.
thanks :)

**Closed** 2015-11-09 19:57 UTC
